Assertion fix.
ICE: Assertion 'mem_pools == NULL' failed at ./jerry-core/mem/mem-poolman.cpp(mem_pools_finalize):89.
Error: ERR_FAILED_INTERNAL_ASSERTION

Add missing ecma_deref_ecma_string() and ecma_dealloc_number() calls.

JerryScript-DCO-1.0-Signed-off-by: Szilard Ledan szledan.u-szeged@partner.samsung.com
JerryScript-DCO-1.0-Signed-off-by: László Langó llango.u-szeged@partner.samsung.com